FROM golang:1.21.0 as builder

ENV ARCH=arm64
ENV OS=linux
#ENV GOPROXY=https://goproxy.cn,direct

WORKDIR /go/src/cloud-route-manager

#COPY go.mod ./go.mod
#COPY go.sum ./go.sum
# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
# RUN go mod tidy

COPY . /go/src/cloud-route-manager

RUN export GOCACHE=/tmp && \
    export GO111MODULE=on && \
    export GOARCH=${ARCH} && \
    export CGO_ENABLED=0 && \
    export GOOS=${OS} && \
	go mod tidy && \
    go build -o /go/bin/cloud-route-manager ./controller

FROM alpine:latest

RUN apk add --no-cache iptables && \
    apk add --no-cache ipset && \
    apk add --no-cache bash

LABEL maintainer="Cloud-Barista Contributors"
WORKDIR /cloud-route-manager
COPY --from=builder /go/bin/cloud-route-manager /cloud-route-manager/controller
RUN chmod +x /cloud-route-manager/controller

ENTRYPOINT ["/cloud-route-manager/controller"]